[general]
anchor = "bottom" # "top" or "bottom"
margin_edge = 5
margin_side_edge = 10
space_between_widgets = 5

[widget_default]
height = 40
border_radius = 12

[time]
format = "%H:%M:%S"

[date]
format = "%A, %d %B %Y"

[widgets.left]
names = ["time", "time", "time", "time"]

[widgets.right]
names = ["time"]